---
sudo: required
services:
  - docker
env:
  global:
    - "SHA=$(git rev-parse HEAD)"
    - "CLOUDSDK_CORE_DISABLE_PROMPTS=1"
before_install:
  - "openssl aes-256-cbc -K $encrypted_6e1b6df37de9_key -iv $encrypted_6e1b6df37de9_iv -in service-account.json.enc -out ./service-account.json -d"
  - "curl https://sdk.cloud.google.com | bash > /dev/null;"
  - "source ~/google-cloud-sdk/path.zsh.inc"
  - "gcloud components update kubectl"
  - "gcloud auth activate-service-account --key-file service_account.json"
  - "gcloud config set project tikitakaenv"
  - "gcloud config set compute/zone us-west2-c"
  - "gcloud container clusters get-credentials tikitakaenv"
  - "echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin"
  - "docker build -t armangurkan1/react-test -f ./client/Dockerfile.dev ./client"
script:
  - "docker run -e CI=true armangurkan1/react-test npm run test"
deploy:
  provider: script
  script: "bash ./deploy.sh"
  on:
    branch: master


